### ISSUE TITLE
Fix image not found error from `/static/` fileserver 🐞

### ISSUE THREAD

**Issue by sarkartanmay393** [sarkartanmay393/RoomReservation-WebApp#9]
No image is showing in any of the pages. Network request shows NotFound 404 status code.

**Comment by akshitadixit** [comment]
You might wanna use `../../static/images/<image-file>`

**Comment by sarkartanmay393** [comment]
@akshitadixit In file server right ? But it doesn't work even with that path also.

**Comment by sarkartanmay393** [comment]
Opened PR: https://github.com/sarkartanmay393/RoomReservation-WebApp/pull/10

@akshitadixit It was a dot and a slash 🥲

**Comment by akshitadixit** [comment]
@sarkartanmay393 I tried 🤷‍♀️
